import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import Footer from '@/components/footer/Footer';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/authOptions';
import Navbar from '@/components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Crafts by Jules',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className="" suppressHydrationWarning>
      <body className={`${inter.className} bg-[#f9f8fb] dark:bg-gray-900`}>
        <Providers>
          <div className="mx-auto flex min-h-screen flex-col">
            <Navbar session={session} />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
